/home/ncmssh0313/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ncmssh0313/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Evaluating Dataset!
| Test Epoch #0	 Accuracy: 49.14%
Training started!
Epoch [  0/1000] Iter[  1/377]	
Acc  47.65625
Epoch [  0/1000] Iter[101/377]	
Acc  49.61324257425743
Epoch [  0/1000] Iter[201/377]	
Acc  50.1865671641791
Epoch [  0/1000] Iter[301/377]	
Acc  50.277720099667775
Training acc =  50.157493368700266
Evaluating Dataset!
| Test Epoch #0	 Accuracy: 54.53%
Saving best!
Training started!
Epoch [  1/1000] Iter[  1/377]	
Acc  51.5625
Epoch [  1/1000] Iter[101/377]	
Acc  51.14480198019802
Epoch [  1/1000] Iter[201/377]	
Acc  51.21268656716418
Traceback (most recent call last):
  File "/home/ncmssh0313/Guiding-Pseudo-labels-with-Uncertainty-Estimation-for-Source-free-Unsupervised-Domain-Adaptation/train_target.py", line 363, in <module>
    train(epoch, net, moco_model, optimizer, train_loader, banks) # train net1
  File "/home/ncmssh0313/Guiding-Pseudo-labels-with-Uncertainty-Estimation-for-Source-free-Unsupervised-Domain-Adaptation/train_target.py", line 157, in train
    for batch_idx, batch in enumerate(trainloader):
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ncmssh0313/Guiding-Pseudo-labels-with-Uncertainty-Estimation-for-Source-free-Unsupervised-Domain-Adaptation/datasets.py", line 229, in __getitem__
    img = Image.open(img)
  File "/home/ncmssh0313/.local/lib/python3.10/site-packages/PIL/Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ncmssh0313/Guiding-Pseudo-labels-with-Uncertainty-Estimation-for-Source-free-Unsupervised-Domain-Adaptation/data/domainnet-126/sketch/candle/sketch_059_000066.jpg'